// code.node/solid/typescript/index.tsx
// Import solid-js facilities
import { render } from "solid-js/web"
import { JSX } from "solid-js/jsx-runtime"

// Import routed components
import { ProcessBlock } from "./pblock"
import { Welcome } from "../resources/components"

// Render components based on URL path
const Router = (): JSX.Element =>  {
  switch(window.location.pathname) {

    case "/flow": 
      return <ProcessBlock />

    default:
      return <Welcome />
  }
}
render(() => <Router />, document.getElementById("app")!)

// code.react/typescript/index.tsx
// a simple router for React components

import React from 'react'
import ReactDOM from 'react-dom'

import { WelcomePage } from './welcome'
import { NotificationPage } from './mtn-notifications'
import { WorkingTimePage } from './mtn-workingtime'

const App: React.FC = () => {
  // Get the current path from the URL
  const currentPath = window.location.pathname

  // Render different components based on the URL
  switch (currentPath) {
    case '/mtn/notification':
      return <NotificationPage />
    case '/mtn/workingtime':
      return <WorkingTimePage />
    default:
      return <WelcomePage /> }}

// render JSX and ReactApp
const app: HTMLElement | null = document.getElementById('ReactApp')
ReactDOM.createRoot(app!).render(<App />)
